import { getInputRaw } from '../../utils';

const input = await getInputRaw(2025, 7);

const sample = `.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............`;
describe('2025 Day 7 Rust', async () => {
  const { part_one, part_two } = await import('./main.rs');
  it('Passes Part 1 Test', () => {
    expect(part_one(sample)).toBe(21);
  }, 15_000);
  it('Passes Part 1', () => {
    expect(part_one(input)).toBe(1_566);
  }, 15_000);
  it('Passes Part 2 Test', () => {
    expect(part_two(sample)).toBe(40n);
  }, 15_000);
  it('Passes Part 2', () => {
    expect(part_two(input)).toBe(5_921_061_943_075n);
  }, 15_000);
});
