[package]
name = "advent-of-code"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.10.2"

[lib]
name = "mainday4"
crate-type = ["cdylib"]
path = "../../2023/04/main-day4.rs"
